// <auto-generated />
using System;
using Alcatraz.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alcatraz.Context.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260614073913_notoriety")]
    partial class notoriety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Alcatraz.Context.Entities.LoginPin", b =>
                {
                    b.Property<string>("Pin")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Pin");

                    b.HasIndex("TokenId");

                    b.ToTable("LoginPins");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.PlayerStatisticsBoard", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("PlayerId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PlayerStatisticBoards");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.PlayerStatisticsBoardValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("PlayerBoardId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("RankingCriterionIndex")
                        .HasColumnType("int");

                    b.Property<string>("ScoreLostForNextSliceJSON")
                        .HasColumnType("longtext");

                    b.Property<string>("SliceScoreJSON")
                        .HasColumnType("longtext");

                    b.Property<string>("ValueJSON")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlayerBoardId");

                    b.ToTable("PlayerStatisticBoardValues");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.SessionToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionTokens");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("NotorietyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerNickName")
                        .HasColumnType("longtext");

                    b.Property<int>("RewardFlags")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.UserRelationship", b =>
                {
                    b.Property<uint>("User1Id")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("User2Id")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ByRelationShip")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Details")
                        .HasColumnType("int unsigned");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("UserRelationships");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.LoginPin", b =>
                {
                    b.HasOne("Alcatraz.Context.Entities.SessionToken", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.PlayerStatisticsBoardValue", b =>
                {
                    b.HasOne("Alcatraz.Context.Entities.PlayerStatisticsBoard", "PlayerBoard")
                        .WithMany("Values")
                        .HasForeignKey("PlayerBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerBoard");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.SessionToken", b =>
                {
                    b.HasOne("Alcatraz.Context.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.UserRelationship", b =>
                {
                    b.HasOne("Alcatraz.Context.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alcatraz.Context.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.PlayerStatisticsBoard", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
