using System;
using Alcatraz.Context;
using Alcatraz.GameServices.Services;
using Microsoft.AspNetCore.Mvc;

namespace Alcatraz.GameServices.Controllers.Ubiservices.V1
{
    [ApiController]
    [Route("v1/users")]
    public class UsersController(IUserService userService, MainDbContext dbContext) : ControllerBase
    {
        [HttpGet("{id}")]
        public IActionResult GetUser(string id, [FromHeader(Name = "Authorization")] string authorization)
        {
            var user = userService.GetByIdGuid(Guid.Parse(id));
            if (user == null)
                return NotFound(new
                {
                    error = "User not found"
                });

            return Ok(new
            {
                userId = user.Guid,
                username = user.PlayerNickName,
                nameOnPlatform = (object)null,
                accountIssues = (object)null,
                communicationOptIn = true,
                communicationThirdPartyOptIn = true,
                country = "US",
                region = (object)null,
                dateCreated = "1970-01-01T00:00:00.0000000Z",
                dateAnonymized = (object)null,
                dateOfBirth = "1970-01-01T00:00:00.0000000Z",
                email = "test@watchdogs.test",
                firstName = user.PlayerNickName,
                gender = (object)null,
                hasAcceptedLegalOptins = true,
                lastName = "",
                preferredLanguage = "en",
                status = new
                {
                    autoGeneratedUsername = false,
                    dateOfBirthApproximated = false,
                    invalidEmail = false,
                    missingRequiredInformation = false,
                    pendingDeactivation = false,
                    targetDeactivationDate = (object)null,
                    recoveringPassword = false,
                    passwordUpdateRequired = false,
                    reserved = false,
                    changeEmailPending = true,
                    inactiveAccount = false,
                    generalStatus = "activated",
                    suspiciousActivity = false,
                    locked = false,
                    minor = false,
                    testAccount = false,
                    phoneActivated = true,
                    phoneSanctioned = false,
                    invalidPhone = false,
                    ageVerification = "notVerified",
                    emailChangeInCooldown = (object)null,
                    stolenAccount = false
                },
                phone = new { number = "*********", countryCallingCode = "01" },
                profiles = new[]
                {
                    new
                    {
                        idOnPlatform = user.Guid,
                        nameOnPlatform = user.PlayerNickName,
                        platformType = "uplay",
                        profileId = user.Guid,
                        userId = user.Guid
                    }
                },
                accountType = "Ubisoft",
                ageGroup = "adult"
            });
        }
    }
}